baseURL = "https://example.org/"
languageCode = "en-us"
title = "Emacs Theme Demo"
theme = "emacs"

[markup.highlight]
noClasses = false

[params]
description = "A demo site for the Emacs Hugo theme"
